### ISSUE TITLE
fail to fetch the source

### ISSUE THREAD

**Issue by Obarun** [jjk-jacky/abs#1]
hello, i think you have a little error here
`git+https://github.com//jjk-jacky/${_pkgname}.git#branch=next`
this is produce an error to download the source file

i have changed by
`git+https://github.com/jjk-jacky/${_pkgname}.git#branch=next`

Regard Eric Vidal

**Comment by jjk-jacky** [comment]
Oops... That would be in anopa-musl-git's PKGBUILD indeed.
Good catch, fixed, thanks!
