### ISSUE TITLE
Patch in s6-musl-git fails to apply

### ISSUE THREAD

**Issue by djpohly** [jjk-jacky/abs#2]
````
patching file src/daemontools-extras/s6-log.c
Hunk #2 succeeded at 734 (offset -6 lines).
Hunk #3 succeeded at 787 (offset -6 lines).
Hunk #4 succeeded at 861 (offset -6 lines).
Hunk #5 FAILED at 961.
Hunk #6 FAILED at 974.
2 out of 6 hunks FAILED -- saving rejects to file src/daemontools-extras/s6-log.c.rej
````
s6's conversion to `struct iovec` in [c60ebd4](https://github.com/skarnet/s6/commit/c60ebd422171808ad58b936914055397bb205bef) appears to be the culprit.

**Comment by jjk-jacky** [comment]
Oh yeah, I still haven't found time to update to the recent skalibs
2.5.0.0 API changes indeed. It's on a todo list ofc...

**Comment by jjk-jacky** [comment]
Rebased patch has been pushed.
