### ISSUE TITLE
Git packages need git in makedepends

### ISSUE THREAD

**Issue by djpohly** [jjk-jacky/abs#3]
According to Arch's [VCS package guidelines](https://wiki.archlinux.org/index.php/VCS_package_guidelines), the tool needed to download sources from version control needs to be included in the `makedepends` array.

This appears to affect:
* anopa-musl-git
* execline-musl-git
* mtCellEdit
* s6-devd-musl-git
* s6-dns-musl-git
* s6-musl-git
* s6-networking-musl-git
* skalibs-musl-git

**Comment by jjk-jacky** [comment]
Right, done, thanks.
